### ISSUE TITLE
Exercises 5-1, 5-3: 'NULL' is not NULL

### ISSUE THREAD

**Issue by smattingly** [csci320/Spritte77#2]
https://github.com/csci320/Spritte77/blob/e29b28d3b67afa07c110c3fbf2484377308636d2/exercise5-1.txt#L24-L26

You have the right idea here, but you are typing `'NULL'` where you want to type `NULL`. With the quotes, you have a string value; without, you have the special non-value. 

Similar issue in 5-3.

**Comment by Spritte77** [comment]
I have sent the new changes to master

**Comment by smattingly** [comment]
@Spritte77 Ok, I will look. But please let me close these Issues; I use them to track progress that maps to gradebook credit.

**Comment by smattingly** [comment]
👍
